### PR TITLE
Interactive layout demo

### PR DESCRIPTION
**Pull request by TheNoim**
Reference: #368 
Still work in progress. 
I need some help, because I don't really understand the use case of `align-content-*`.
Also the name of the file + description need to be changed. Need some suggestions.

### CODE REVIEW

**Comment by johnleider** [comment]
I'd like to move this into its own page or as the usage example. Looks great so far.

**Comment by KaelWD** [comment]
> `align-content-*`

https://css-tricks.com/snippets/css/a-guide-to-flexbox/#article-header-id-8

**Comment by TheNoim** [comment]
@KaelWD But is this not exactly the same as `align-*`?

**Comment by KaelWD** [comment]
No, look at the link. `align-content-*` controls the alignment when it's wrapped.

**Comment by TheNoim** [comment]
I excluded `align-content` because I think it wouldn't fit into this playground/example. I am pleased with the result. You can look into it.

**Pull request merged**
