### PR TITLE
Initial Commit for nl-NL (Dutch) Translation

### PR DESCRIPTION
**Pull request by jdriesen**
Sorry about the typo's in the commit comments.
Will take care about it in the future...

### CODE REVIEW

**Comment by KaelWD** [comment]
Don't include files that have not been translated yet. Any missing strings will automatically fall back to english.

**Comment by jdriesen** [comment]
@KaelWD ...
"Removing all files which have not yet been translated" ...
Does that include "remove the references in the index.js files" as well ?
'or should I better 'comment" the references in the index.js files ?

Grtz,
Johnny

**Comment by KaelWD** [comment]
That's up to you. Commenting them out with `// TODO: ` would make it easier to see what still needs to be done however.

**Comment by jdriesen** [comment]
OK. Cool. Thanks.
As mentioned yesterday on Discord, I'm rather a rather newbie when it's about "participating to a big project" ...

Thanks for your patience and help, @KaelWD  .

**Pull request closed without merging**
