### PR TITLE
[Docs Update] Added note about two new slots

### PR DESCRIPTION
**Pull request by DCzajkowski**
Documentation for the https://github.com/vuetifyjs/vuetify/pull/4691 pull request.

### CODE REVIEW

**Comment by praveenpuglia** [comment]
Looks good to me. It'll get merged once the referenced PR is merged there. Thanks :)

**Comment by praveenpuglia** [comment]
Can you please update it with base branch and then I can merge this?

**Comment by DCzajkowski** [comment]
Of course! Done 😉

**Comment by praveenpuglia** [comment]
It got out of sync again so I just merged dev into it again!

**Comment by KaelWD** [comment]
This will need an update to https://github.com/vuetifyjs/api-generator too.

**Comment by DCzajkowski** [comment]
Done 👍

**Comment by praveenpuglia** [comment]
Can we merge this now @KaelWD ?

**Comment by DCzajkowski** [comment]
v1.2.0 is out. Can we get this merged? 😇

**Comment by KaelWD** [comment]
Why the fuck did that close it lol

**Comment by DCzajkowski** [comment]
I guess GitHub misunderstood word `Fixes`

**Pull request merged**
