### PR TITLE
Rework country flags with retina support

### PR DESCRIPTION
**Pull request by ihororlovskyi**
Features:
- retina support
- svg base64
- circled material design flags from free pack
- borders no needed (issue: https://github.com/vuetifyjs/vuetifyjs.com/issues/274)

result screenshot: https://i.imgur.com/pwEISo1.jpg

### CODE REVIEW

**Comment by johnleider** [comment]
Move the images to an external file that is referenced by the language input. The image references should probably have never been in the language files.

**Comment by ihororlovskyi** [comment]
ok, thanks,
work in progress

**Comment by bdeo** [comment]
Is all thats left here to relocate the images?

**Comment by ihororlovskyi** [comment]
changes are added, please check

**Comment by johnleider** [comment]
Everything looks good. Can we go back to rectangle for the selected flag? I'm not a huge fan of the circle.

**Comment by johnleider** [comment]
Closing due to inactivity.

**Pull request closed without merging**
