### PR TITLE
Pagination Component: add more items to vuetify tabs

### PR DESCRIPTION
**Pull request by DakshMiglani**
Add more items so that we can see pagination controls on high res screens.

### CODE REVIEW

**Comment by KaelWD** [comment]
Duplicate of #635

**Comment by DakshMiglani** [comment]
@KaelWD actually they are different PRs for two different components.

**Comment by DakshMiglani** [comment]
One is for pagination the other one is for custom icons.

**Comment by DakshMiglani** [comment]
@jacekkarczmarczyk done.

**Comment by johnleider** [comment]
Thank you for your contribution and interest in improving Vuetify!

**Pull request merged**
