### PR TITLE
Add grid list sample

### PR DESCRIPTION
**Pull request by ebisbe**
Samples like https://quasar-framework.org/components/action-sheet.html . 

I wanted to do the four versions like in the link. I think that adding another action sheet with v-avatar using v-icons is too obvious. I could add a sublist with a separator in the first example with Delete, Share, Edit actions to show case the usage of icons in avatars.

The grid list is trickier to handle because we need to use cards with a predefined height and we don't have any type of button with icon above text, right?

### CODE REVIEW

**Comment by johnleider** [comment]
The images need to have a size specified so that they do not grow indefinitely.

image

**Comment by johnleider** [comment]
I'm not 100% sold on the addition. It doesn't feel very material with how the ripple is located on the grid section

**Comment by ebisbe** [comment]
yes, me neither. I think it should be done in another way. Not sure how.

**Comment by johnleider** [comment]
Closing due to inactivity

**Pull request closed without merging**
