### PR TITLE
update Chinese translation for home and store pages.

### PR DESCRIPTION
**Pull request by ElderJames**

### CODE REVIEW

**Comment by KaelWD** [comment]
Why is this targeted to the 1.1 branch?

**Comment by ElderJames** [comment]
sorry,I thought this was the pre-release branch...

**Comment by KaelWD** [comment]
It's fine, we've decided not to archive v1.0. We do have a new structure for language files though if you could update this PR.

**Comment by ElderJames** [comment]
Ok, I will update in these days 😃

**Pull request merged**
