### PR TITLE
[wip] ja translation

### PR DESCRIPTION
**Pull request by dojineko**
## Work in Progress

add japanese translation

### CODE REVIEW

**Comment by dojineko** [comment]
is `vuetify/es5/util/easing-patterns` disappeared? 🤔 

```
* vuetify/es5/util/easing-patterns in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./examples/scrolling/usage.vue
```

**Comment by KaelWD** [comment]
No, it's a new feature in beta 7. You'll have to use `yarn link` until it's released.

**Comment by dojineko** [comment]
@KaelWD i did it thx~ 😇

**Comment by johnleider** [comment]
Is this still being worked on?

**Comment by dojineko** [comment]
still working 🤠

**Comment by dojineko** [comment]
@bad4iz sorry for rebased...;😅

**Pull request merged**
