### PR TITLE
Feature/translation into russian

### PR DESCRIPTION
**Pull request by bad4iz**
Hello!
Your Vuetify is super. I am delighted.
I want to popularize Vuetify in Russia.
Began to translate. While translated two pages - Home and Quick start

thank you for the Vuetify

### CODE REVIEW

**Comment by johnleider** [comment]
You do not have to include files that have not been translated, it will automatically fall back to english if the language has none available. Can you update your PR please? Thank you.

**Comment by bad4iz** [comment]
corrected
.... deleted files that have not been translated.
.... added another translation of the file.

**Comment by bad4iz** [comment]
I'm connecting my Russian language so

_./i18n/index.js_
```js
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import en from'./en-US'
import ru from'./ru-RU'

Vue.use(VueI18n)

export function createI18n () {
  return new VueI18n({
    locale: 'ru-RU',
    fallbackLocale: 'en-US',
    messages: {
      'en-US': en,
      'ru-RU': ru
    }
  })
}
```
how to do it globally?

**Comment by bad4iz** [comment]
Thank you. I understood.
added switching to languages in the translation menu

**Comment by nekosaur** [comment]
Could you possibly pull out the changes to AppToolbar to a separate PR?

**Comment by KaelWD** [comment]
And don't modify any other languages either, you have a bunch of changes to en-US in here.

**Comment by bad4iz** [comment]
I'm just confused all merged into one. I'd better delete and re-do?

**Comment by KaelWD** [comment]
I never said that, you can just rebase them out. Or revert the commits if there was nothing else in them.

**Comment by bad4iz** [comment]
Мне лучше открыть новый PR

**Pull request closed without merging**
